
// This file has been generated by the GUI designer. Do not modify.

public partial class MainWindow
{
	private global::Gtk.VBox vbox1;
	
	private global::Gtk.Frame frame1;
	
	private global::Gtk.Alignment GtkAlignment;
	
	private global::Gtk.HBox hbox2;
	
	private global::Gtk.ScrolledWindow GtkScrolledWindow;
	
	private global::Gtk.TreeView treeViewZimFiles;
	
	private global::Gtk.VButtonBox vbuttonbox2;
	
	private global::Gtk.Button buttonAddZimFile;
	
	private global::Gtk.Button buttonClearZimFiles;
	
	private global::Gtk.Label GtkLabel2;
	
	private global::Gtk.Frame frame2;
	
	private global::Gtk.Alignment GtkAlignment1;
	
	private global::Gtk.HBox hbox3;
	
	private global::Gtk.VButtonBox vbuttonbox3;
	
	private global::Gtk.Button buttonAffFile;
	
	private global::Gtk.Button buttonDicFile;
	
	private global::Gtk.VBox vbox3;
	
	private global::Gtk.Entry entryAffFile;
	
	private global::Gtk.Entry entryDicFile;
	
	private global::Gtk.Label GtkLabel5;
	
	private global::Gtk.Frame frame3;
	
	private global::Gtk.Alignment GtkAlignment2;
	
	private global::Gtk.HBox hbox4;
	
	private global::Gtk.VBox vbox4;
	
	private global::Gtk.CheckButton checkbuttonAllWords;
	
	private global::Gtk.CheckButton checkbuttonSpellChecked;
	
	private global::Gtk.CheckButton checkbuttonUppercase;
	
	private global::Gtk.VBox vbox5;
	
	private global::Gtk.Entry entryAllWords;
	
	private global::Gtk.Entry entrySpellChecked;
	
	private global::Gtk.Entry entryUppercase;
	
	private global::Gtk.Label GtkLabel9;
	
	private global::Gtk.HBox hbox5;
	
	private global::Gtk.ProgressBar progressbar1;
	
	private global::Gtk.Button buttonStart;

	protected virtual void Build ()
	{
		global::Stetic.Gui.Initialize (this);
		// Widget MainWindow
		this.Name = "MainWindow";
		this.Title = global::Mono.Unix.Catalog.GetString ("Woerterbuch");
		this.WindowPosition = ((global::Gtk.WindowPosition)(4));
		// Container child MainWindow.Gtk.Container+ContainerChild
		this.vbox1 = new global::Gtk.VBox ();
		this.vbox1.Name = "vbox1";
		this.vbox1.Spacing = 6;
		// Container child vbox1.Gtk.Box+BoxChild
		this.frame1 = new global::Gtk.Frame ();
		this.frame1.Name = "frame1";
		this.frame1.ShadowType = ((global::Gtk.ShadowType)(0));
		this.frame1.BorderWidth = ((uint)(6));
		// Container child frame1.Gtk.Container+ContainerChild
		this.GtkAlignment = new global::Gtk.Alignment (0F, 0F, 1F, 1F);
		this.GtkAlignment.Name = "GtkAlignment";
		this.GtkAlignment.LeftPadding = ((uint)(12));
		// Container child GtkAlignment.Gtk.Container+ContainerChild
		this.hbox2 = new global::Gtk.HBox ();
		this.hbox2.Name = "hbox2";
		this.hbox2.Spacing = 6;
		// Container child hbox2.Gtk.Box+BoxChild
		this.GtkScrolledWindow = new global::Gtk.ScrolledWindow ();
		this.GtkScrolledWindow.Name = "GtkScrolledWindow";
		this.GtkScrolledWindow.ShadowType = ((global::Gtk.ShadowType)(1));
		// Container child GtkScrolledWindow.Gtk.Container+ContainerChild
		this.treeViewZimFiles = new global::Gtk.TreeView ();
		this.treeViewZimFiles.CanFocus = true;
		this.treeViewZimFiles.Name = "treeViewZimFiles";
		this.GtkScrolledWindow.Add (this.treeViewZimFiles);
		this.hbox2.Add (this.GtkScrolledWindow);
		global::Gtk.Box.BoxChild w2 = ((global::Gtk.Box.BoxChild)(this.hbox2 [this.GtkScrolledWindow]));
		w2.Position = 0;
		// Container child hbox2.Gtk.Box+BoxChild
		this.vbuttonbox2 = new global::Gtk.VButtonBox ();
		this.vbuttonbox2.Name = "vbuttonbox2";
		this.vbuttonbox2.LayoutStyle = ((global::Gtk.ButtonBoxStyle)(3));
		// Container child vbuttonbox2.Gtk.ButtonBox+ButtonBoxChild
		this.buttonAddZimFile = new global::Gtk.Button ();
		this.buttonAddZimFile.CanFocus = true;
		this.buttonAddZimFile.Name = "buttonAddZimFile";
		this.buttonAddZimFile.UseUnderline = true;
		this.buttonAddZimFile.BorderWidth = ((uint)(6));
		this.buttonAddZimFile.Label = global::Mono.Unix.Catalog.GetString ("Add ZIM files");
		this.vbuttonbox2.Add (this.buttonAddZimFile);
		global::Gtk.ButtonBox.ButtonBoxChild w3 = ((global::Gtk.ButtonBox.ButtonBoxChild)(this.vbuttonbox2 [this.buttonAddZimFile]));
		w3.Expand = false;
		w3.Fill = false;
		// Container child vbuttonbox2.Gtk.ButtonBox+ButtonBoxChild
		this.buttonClearZimFiles = new global::Gtk.Button ();
		this.buttonClearZimFiles.CanFocus = true;
		this.buttonClearZimFiles.Name = "buttonClearZimFiles";
		this.buttonClearZimFiles.UseUnderline = true;
		this.buttonClearZimFiles.BorderWidth = ((uint)(6));
		this.buttonClearZimFiles.Label = global::Mono.Unix.Catalog.GetString ("Clear ZIM file list");
		this.vbuttonbox2.Add (this.buttonClearZimFiles);
		global::Gtk.ButtonBox.ButtonBoxChild w4 = ((global::Gtk.ButtonBox.ButtonBoxChild)(this.vbuttonbox2 [this.buttonClearZimFiles]));
		w4.Position = 1;
		w4.Expand = false;
		w4.Fill = false;
		this.hbox2.Add (this.vbuttonbox2);
		global::Gtk.Box.BoxChild w5 = ((global::Gtk.Box.BoxChild)(this.hbox2 [this.vbuttonbox2]));
		w5.Position = 1;
		w5.Expand = false;
		w5.Fill = false;
		this.GtkAlignment.Add (this.hbox2);
		this.frame1.Add (this.GtkAlignment);
		this.GtkLabel2 = new global::Gtk.Label ();
		this.GtkLabel2.Name = "GtkLabel2";
		this.GtkLabel2.LabelProp = global::Mono.Unix.Catalog.GetString ("<b>ZIM File List</b>");
		this.GtkLabel2.UseMarkup = true;
		this.frame1.LabelWidget = this.GtkLabel2;
		this.vbox1.Add (this.frame1);
		global::Gtk.Box.BoxChild w8 = ((global::Gtk.Box.BoxChild)(this.vbox1 [this.frame1]));
		w8.Position = 0;
		// Container child vbox1.Gtk.Box+BoxChild
		this.frame2 = new global::Gtk.Frame ();
		this.frame2.Name = "frame2";
		this.frame2.ShadowType = ((global::Gtk.ShadowType)(0));
		this.frame2.BorderWidth = ((uint)(6));
		// Container child frame2.Gtk.Container+ContainerChild
		this.GtkAlignment1 = new global::Gtk.Alignment (0F, 0F, 1F, 1F);
		this.GtkAlignment1.Name = "GtkAlignment1";
		this.GtkAlignment1.LeftPadding = ((uint)(12));
		// Container child GtkAlignment1.Gtk.Container+ContainerChild
		this.hbox3 = new global::Gtk.HBox ();
		this.hbox3.Name = "hbox3";
		this.hbox3.Spacing = 6;
		// Container child hbox3.Gtk.Box+BoxChild
		this.vbuttonbox3 = new global::Gtk.VButtonBox ();
		this.vbuttonbox3.Name = "vbuttonbox3";
		this.vbuttonbox3.LayoutStyle = ((global::Gtk.ButtonBoxStyle)(1));
		// Container child vbuttonbox3.Gtk.ButtonBox+ButtonBoxChild
		this.buttonAffFile = new global::Gtk.Button ();
		this.buttonAffFile.CanFocus = true;
		this.buttonAffFile.Name = "buttonAffFile";
		this.buttonAffFile.UseUnderline = true;
		this.buttonAffFile.Label = global::Mono.Unix.Catalog.GetString ("AFF file");
		this.vbuttonbox3.Add (this.buttonAffFile);
		global::Gtk.ButtonBox.ButtonBoxChild w9 = ((global::Gtk.ButtonBox.ButtonBoxChild)(this.vbuttonbox3 [this.buttonAffFile]));
		w9.Expand = false;
		w9.Fill = false;
		// Container child vbuttonbox3.Gtk.ButtonBox+ButtonBoxChild
		this.buttonDicFile = new global::Gtk.Button ();
		this.buttonDicFile.CanFocus = true;
		this.buttonDicFile.Name = "buttonDicFile";
		this.buttonDicFile.UseUnderline = true;
		this.buttonDicFile.Label = global::Mono.Unix.Catalog.GetString ("DIC file");
		this.vbuttonbox3.Add (this.buttonDicFile);
		global::Gtk.ButtonBox.ButtonBoxChild w10 = ((global::Gtk.ButtonBox.ButtonBoxChild)(this.vbuttonbox3 [this.buttonDicFile]));
		w10.Position = 1;
		w10.Expand = false;
		w10.Fill = false;
		this.hbox3.Add (this.vbuttonbox3);
		global::Gtk.Box.BoxChild w11 = ((global::Gtk.Box.BoxChild)(this.hbox3 [this.vbuttonbox3]));
		w11.Position = 0;
		w11.Expand = false;
		w11.Fill = false;
		// Container child hbox3.Gtk.Box+BoxChild
		this.vbox3 = new global::Gtk.VBox ();
		this.vbox3.Name = "vbox3";
		this.vbox3.Spacing = 6;
		// Container child vbox3.Gtk.Box+BoxChild
		this.entryAffFile = new global::Gtk.Entry ();
		this.entryAffFile.CanFocus = true;
		this.entryAffFile.Name = "entryAffFile";
		this.entryAffFile.Text = global::Mono.Unix.Catalog.GetString ("/usr/share/hunspell/de_DE.aff");
		this.entryAffFile.IsEditable = true;
		this.entryAffFile.InvisibleChar = '●';
		this.vbox3.Add (this.entryAffFile);
		global::Gtk.Box.BoxChild w12 = ((global::Gtk.Box.BoxChild)(this.vbox3 [this.entryAffFile]));
		w12.Position = 0;
		w12.Expand = false;
		w12.Fill = false;
		// Container child vbox3.Gtk.Box+BoxChild
		this.entryDicFile = new global::Gtk.Entry ();
		this.entryDicFile.CanFocus = true;
		this.entryDicFile.Name = "entryDicFile";
		this.entryDicFile.Text = global::Mono.Unix.Catalog.GetString ("/usr/share/hunspell/de_DE.dic");
		this.entryDicFile.IsEditable = true;
		this.entryDicFile.InvisibleChar = '●';
		this.vbox3.Add (this.entryDicFile);
		global::Gtk.Box.BoxChild w13 = ((global::Gtk.Box.BoxChild)(this.vbox3 [this.entryDicFile]));
		w13.Position = 1;
		w13.Expand = false;
		w13.Fill = false;
		this.hbox3.Add (this.vbox3);
		global::Gtk.Box.BoxChild w14 = ((global::Gtk.Box.BoxChild)(this.hbox3 [this.vbox3]));
		w14.Position = 1;
		this.GtkAlignment1.Add (this.hbox3);
		this.frame2.Add (this.GtkAlignment1);
		this.GtkLabel5 = new global::Gtk.Label ();
		this.GtkLabel5.Name = "GtkLabel5";
		this.GtkLabel5.LabelProp = global::Mono.Unix.Catalog.GetString ("<b>Hunspell</b>");
		this.GtkLabel5.UseMarkup = true;
		this.frame2.LabelWidget = this.GtkLabel5;
		this.vbox1.Add (this.frame2);
		global::Gtk.Box.BoxChild w17 = ((global::Gtk.Box.BoxChild)(this.vbox1 [this.frame2]));
		w17.Position = 1;
		w17.Expand = false;
		w17.Fill = false;
		// Container child vbox1.Gtk.Box+BoxChild
		this.frame3 = new global::Gtk.Frame ();
		this.frame3.Name = "frame3";
		this.frame3.ShadowType = ((global::Gtk.ShadowType)(0));
		this.frame3.BorderWidth = ((uint)(6));
		// Container child frame3.Gtk.Container+ContainerChild
		this.GtkAlignment2 = new global::Gtk.Alignment (0F, 0F, 1F, 1F);
		this.GtkAlignment2.Name = "GtkAlignment2";
		this.GtkAlignment2.LeftPadding = ((uint)(12));
		// Container child GtkAlignment2.Gtk.Container+ContainerChild
		this.hbox4 = new global::Gtk.HBox ();
		this.hbox4.Name = "hbox4";
		this.hbox4.Spacing = 6;
		// Container child hbox4.Gtk.Box+BoxChild
		this.vbox4 = new global::Gtk.VBox ();
		this.vbox4.Name = "vbox4";
		this.vbox4.Spacing = 6;
		// Container child vbox4.Gtk.Box+BoxChild
		this.checkbuttonAllWords = new global::Gtk.CheckButton ();
		this.checkbuttonAllWords.CanFocus = true;
		this.checkbuttonAllWords.Name = "checkbuttonAllWords";
		this.checkbuttonAllWords.Label = global::Mono.Unix.Catalog.GetString ("All words");
		this.checkbuttonAllWords.Active = true;
		this.checkbuttonAllWords.DrawIndicator = true;
		this.checkbuttonAllWords.UseUnderline = true;
		this.vbox4.Add (this.checkbuttonAllWords);
		global::Gtk.Box.BoxChild w18 = ((global::Gtk.Box.BoxChild)(this.vbox4 [this.checkbuttonAllWords]));
		w18.Position = 0;
		w18.Expand = false;
		w18.Fill = false;
		// Container child vbox4.Gtk.Box+BoxChild
		this.checkbuttonSpellChecked = new global::Gtk.CheckButton ();
		this.checkbuttonSpellChecked.CanFocus = true;
		this.checkbuttonSpellChecked.Name = "checkbuttonSpellChecked";
		this.checkbuttonSpellChecked.Label = global::Mono.Unix.Catalog.GetString ("Spell checked");
		this.checkbuttonSpellChecked.Active = true;
		this.checkbuttonSpellChecked.DrawIndicator = true;
		this.checkbuttonSpellChecked.UseUnderline = true;
		this.vbox4.Add (this.checkbuttonSpellChecked);
		global::Gtk.Box.BoxChild w19 = ((global::Gtk.Box.BoxChild)(this.vbox4 [this.checkbuttonSpellChecked]));
		w19.Position = 1;
		w19.Expand = false;
		w19.Fill = false;
		// Container child vbox4.Gtk.Box+BoxChild
		this.checkbuttonUppercase = new global::Gtk.CheckButton ();
		this.checkbuttonUppercase.CanFocus = true;
		this.checkbuttonUppercase.Name = "checkbuttonUppercase";
		this.checkbuttonUppercase.Label = global::Mono.Unix.Catalog.GetString ("Uppercase spell checked");
		this.checkbuttonUppercase.Active = true;
		this.checkbuttonUppercase.DrawIndicator = true;
		this.checkbuttonUppercase.UseUnderline = true;
		this.vbox4.Add (this.checkbuttonUppercase);
		global::Gtk.Box.BoxChild w20 = ((global::Gtk.Box.BoxChild)(this.vbox4 [this.checkbuttonUppercase]));
		w20.Position = 2;
		w20.Expand = false;
		w20.Fill = false;
		this.hbox4.Add (this.vbox4);
		global::Gtk.Box.BoxChild w21 = ((global::Gtk.Box.BoxChild)(this.hbox4 [this.vbox4]));
		w21.Position = 0;
		w21.Expand = false;
		// Container child hbox4.Gtk.Box+BoxChild
		this.vbox5 = new global::Gtk.VBox ();
		this.vbox5.Name = "vbox5";
		this.vbox5.Spacing = 6;
		// Container child vbox5.Gtk.Box+BoxChild
		this.entryAllWords = new global::Gtk.Entry ();
		this.entryAllWords.CanFocus = true;
		this.entryAllWords.Name = "entryAllWords";
		this.entryAllWords.Text = global::Mono.Unix.Catalog.GetString ("word_list_all.txt");
		this.entryAllWords.IsEditable = true;
		this.entryAllWords.InvisibleChar = '●';
		this.vbox5.Add (this.entryAllWords);
		global::Gtk.Box.BoxChild w22 = ((global::Gtk.Box.BoxChild)(this.vbox5 [this.entryAllWords]));
		w22.Position = 0;
		w22.Expand = false;
		w22.Fill = false;
		// Container child vbox5.Gtk.Box+BoxChild
		this.entrySpellChecked = new global::Gtk.Entry ();
		this.entrySpellChecked.CanFocus = true;
		this.entrySpellChecked.Name = "entrySpellChecked";
		this.entrySpellChecked.Text = global::Mono.Unix.Catalog.GetString ("word_list_spell_checked.txt");
		this.entrySpellChecked.IsEditable = true;
		this.entrySpellChecked.InvisibleChar = '●';
		this.vbox5.Add (this.entrySpellChecked);
		global::Gtk.Box.BoxChild w23 = ((global::Gtk.Box.BoxChild)(this.vbox5 [this.entrySpellChecked]));
		w23.Position = 1;
		w23.Expand = false;
		w23.Fill = false;
		// Container child vbox5.Gtk.Box+BoxChild
		this.entryUppercase = new global::Gtk.Entry ();
		this.entryUppercase.CanFocus = true;
		this.entryUppercase.Name = "entryUppercase";
		this.entryUppercase.Text = global::Mono.Unix.Catalog.GetString ("word_list_uppercase_spell_checked.txt");
		this.entryUppercase.IsEditable = true;
		this.entryUppercase.InvisibleChar = '●';
		this.vbox5.Add (this.entryUppercase);
		global::Gtk.Box.BoxChild w24 = ((global::Gtk.Box.BoxChild)(this.vbox5 [this.entryUppercase]));
		w24.Position = 2;
		w24.Expand = false;
		w24.Fill = false;
		this.hbox4.Add (this.vbox5);
		global::Gtk.Box.BoxChild w25 = ((global::Gtk.Box.BoxChild)(this.hbox4 [this.vbox5]));
		w25.Position = 1;
		this.GtkAlignment2.Add (this.hbox4);
		this.frame3.Add (this.GtkAlignment2);
		this.GtkLabel9 = new global::Gtk.Label ();
		this.GtkLabel9.Name = "GtkLabel9";
		this.GtkLabel9.LabelProp = global::Mono.Unix.Catalog.GetString ("<b>Word Lists</b>");
		this.GtkLabel9.UseMarkup = true;
		this.frame3.LabelWidget = this.GtkLabel9;
		this.vbox1.Add (this.frame3);
		global::Gtk.Box.BoxChild w28 = ((global::Gtk.Box.BoxChild)(this.vbox1 [this.frame3]));
		w28.Position = 2;
		w28.Expand = false;
		w28.Fill = false;
		// Container child vbox1.Gtk.Box+BoxChild
		this.hbox5 = new global::Gtk.HBox ();
		this.hbox5.Name = "hbox5";
		this.hbox5.Spacing = 6;
		// Container child hbox5.Gtk.Box+BoxChild
		this.progressbar1 = new global::Gtk.ProgressBar ();
		this.progressbar1.Name = "progressbar1";
		this.hbox5.Add (this.progressbar1);
		global::Gtk.Box.BoxChild w29 = ((global::Gtk.Box.BoxChild)(this.hbox5 [this.progressbar1]));
		w29.Position = 0;
		w29.Padding = ((uint)(10));
		// Container child hbox5.Gtk.Box+BoxChild
		this.buttonStart = new global::Gtk.Button ();
		this.buttonStart.CanFocus = true;
		this.buttonStart.Name = "buttonStart";
		this.buttonStart.UseUnderline = true;
		this.buttonStart.Label = global::Mono.Unix.Catalog.GetString ("  Start  ");
		this.hbox5.Add (this.buttonStart);
		global::Gtk.Box.BoxChild w30 = ((global::Gtk.Box.BoxChild)(this.hbox5 [this.buttonStart]));
		w30.Position = 1;
		w30.Expand = false;
		w30.Fill = false;
		w30.Padding = ((uint)(10));
		this.vbox1.Add (this.hbox5);
		global::Gtk.Box.BoxChild w31 = ((global::Gtk.Box.BoxChild)(this.vbox1 [this.hbox5]));
		w31.Position = 3;
		w31.Expand = false;
		w31.Fill = false;
		w31.Padding = ((uint)(10));
		this.Add (this.vbox1);
		if ((this.Child != null)) {
			this.Child.ShowAll ();
		}
		this.DefaultWidth = 741;
		this.DefaultHeight = 489;
		this.Show ();
		this.DeleteEvent += new global::Gtk.DeleteEventHandler (this.OnDeleteEvent);
		this.buttonAddZimFile.Clicked += new global::System.EventHandler (this.AddZimFiles);
		this.buttonClearZimFiles.Clicked += new global::System.EventHandler (this.ClearZimFileList);
		this.buttonStart.Clicked += new global::System.EventHandler (this.Start);
	}
}
